create table if not exists public.contact_submissions (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 80),
  email text not null check (char_length(email) between 3 and 254),
  company text check (company is null or char_length(company) <= 120),
  subject text not null check (char_length(subject) between 1 and 120),
  message text not null check (char_length(message) between 10 and 3000),
  status text not null default 'new' check (status in ('new', 'read', 'replied', 'archived')),
  created_at timestamptz not null default now()
);
create table if not exists public.admin_emails (email text primary key, created_at timestamptz not null default now());
alter table public.contact_submissions enable row level security;
alter table public.admin_emails enable row level security;
create or replace function public.is_portfolio_admin() returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.admin_emails where lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')));
$$;
revoke all on function public.is_portfolio_admin() from public;
grant execute on function public.is_portfolio_admin() to authenticated;
create policy "Anyone can submit contact form" on public.contact_submissions for insert to anon, authenticated with check (status = 'new' and char_length(name) between 1 and 80 and char_length(email) between 3 and 254 and char_length(subject) between 1 and 120 and char_length(message) between 10 and 3000);
create policy "Admins can read submissions" on public.contact_submissions for select to authenticated using (public.is_portfolio_admin());
create policy "Admins can update submissions" on public.contact_submissions for update to authenticated using (public.is_portfolio_admin()) with check (public.is_portfolio_admin());
create index if not exists contact_submissions_created_at_idx on public.contact_submissions (created_at desc);
